CHANGELOG.md, Cargo.lock, Cargo.toml, evergreen.landscape.yml, evergreen.yml, src/lib.rs, src/main.rs, src/resmoke/resmoke_proxy.rs, src/task_types/resmoke_tasks.rs, tests/data/evergreen.yml, tests/data/sample_evergreen_auth.yml, tests/data/sample_expansions.yml, tests/data/tests/test_0.js, tests/data/tests/test_1.js, tests/data/tests/test_10.js, tests/data/tests/test_11.js, tests/data/tests/test_12.js, tests/data/tests/test_13.js, tests/data/tests/test_14.js, tests/data/tests/test_2.js, tests/data/tests/test_3.js, tests/data/tests/test_4.js, tests/data/tests/test_5.js, tests/data/tests/test_6.js, tests/data/tests/test_7.js, tests/data/tests/test_8.js, tests/data/tests/test_9.js, tests/integration_test.rs, tests/mocks/resmoke.py
This adds 2 new tests alongs with some infrastructure to mock some things out.
* The first test is an integration test that runs againsta snapshot of the server codebase's evergreen.yml and tries to generate all the configuration for it. 
* The second test uses a tool to make sure that the Cargo.toml version and the changelog have been updated (similar to what we do in other tools).
=> DAG-1693: Add integration tests

CHANGELOG.md, Cargo.lock, Cargo.toml, src/task_types/resmoke_tasks.rs
Randomizing only when there are no historic data seems not enough. While testing the latest version of task generator, I still got a [sub-suite](https://evergreen.mongodb.com/task/mongodb_mongo_master_enterprise_rhel_80_64_bit_multiversion_replica_sets_last_lts_4_enterprise_patch_ca8d1708e9fb26734691a177d79bfdc78febc7c5_62bea7cd850e614cd4a73a8d_22_07_01_07_53_38/0##comparehashes=ca8d1708e9fb26734691a177d79bfdc78febc7c5&threads=maxonly) with a bunch of "tenant_migration" tests, which end up being task timeout.
I guess we should randomize the order of tests in all cases.
=> DAG-1899 Randomize test order when creating all resmoke sub-tasks

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/evergreen/evg_config_utils.rs, src/evergreen_names.rs, src/lib.rs, src/task_types/burn_in_tests.rs
The original burn_in_tags python script: https://github.com/mongodb/mongo/blob/f4de1bd3b7de8b3e93d7d051cbfe8544df71112f/buildscripts/burn_in_tags.py
=> DAG-1928: Add support for generating burn_in_tags

CHANGELOG.md, Cargo.lock, Cargo.toml, src/evergreen/evg_config_utils.rs, src/evergreen_names.rs, src/lib.rs, src/services/config_extraction.rs, src/task_types/burn_in_tests.rs, src/task_types/fuzzer_tasks.rs, src/task_types/resmoke_config_writer.rs, src/task_types/resmoke_tasks.rs, src/utils/task_name.rs, tests/integration_test.rs
After these changes a version generation for mongodb-mongo-master project has increased from ~337 sec to ~372 secs on my local machine:
```
{"timestamp":"2022-08-01T10:30:16.525079Z","level":"INFO","fields":{"message":"generation completed: 337 seconds"},"target":"mongo_task_generator"}
```
```
{"timestamp":"2022-08-01T10:39:08.927945Z","level":"INFO","fields":{"message":"generation completed: 372 seconds"},"target":"mongo_task_generator"}
```
Currently in evergreen it generates the version in ~143 seconds:
https://evergreen.mongodb.com/task_log_raw/mongodb_mongo_master_generate_tasks_for_version_version_gen_99286ff7b1f837df8449ef990b881c3ed1e3a64b_22_08_01_04_38_52/0?type=T#L915
```
{"timestamp":"2022-08-01T04:45:40.350646Z","level":"INFO","fields":{"message":"generation completed: 143 …
```
=> DAG-1940 Generate tasks separately for Windows, MacOS, Linux distro groups

.gitignore, CHANGELOG.md, Cargo.lock, Cargo.toml, src/task_types/resmoke_tasks.rs
New task splitting solution does the following steps:
1. Sort tests by the runtime descending. Tests without historic runtime data are placed at the end of the list.
2. Iterate through the sorted list of tests and put each test into the subsuite with the least total runtime of tests that are already in the subsuite on the current iteration.
Evergreen patch: https://spruce.mongodb.com/version/62fce37f1e2d1770cae85cca
Evergreen patch nightly: https://spruce.mongodb.com/version/62fce3e1a4cf471e9da1ff43
Version gen runtime on nightly project is almost the same:
- waterfall: https://evergreen.mongodb.com/task_log_raw/mongodb_mongo_master_nightly_generate_tasks_for_version_version_gen_fa516c72b33889815888a15b787feec5fccf3138_22_08_15_00_08_23/0?type=T#L1242
- patch: …
=> DAG-1967 Improve task splitting based on historic tests runtime

CHANGELOG.md, Cargo.lock, Cargo.toml, src/task_types/resmoke_tasks.rs
Follow-up change after [DAG-1967](https://jira.mongodb.org/browse/DAG-1967).
Evergreen patch: https://spruce.mongodb.com/version/62ff60ea2fbabe6d0b390036/task-duration?duration=DESC
Evergreen patch nightly: https://spruce.mongodb.com/version/62ff60f1e3c33116292f43ea/task-duration?duration=DESC
=> DAG-1986 Distribute tests without historic runtime data evenly between subsuites

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/generating_tasks.md, src/lib.rs, src/main.rs, src/resmoke/burn_in_proxy.rs, tests/integration_test.rs, tests/mocks/burn_in_tests.py
When `--burn-in` is passed, only burn_in tasks are generated. Otherwise all the other tasks are generated.
=> DAG-1992 Generate only burn_in tasks when --burn-in is passed

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/generating_tasks.md, src/evergreen_names.rs, src/lib.rs, src/task_types/burn_in_tests.rs, tests/data/burn_in/evergreen_with_empty_burn_in_variants.yml, tests/data/burn_in/evergreen_with_no_burn_in_distro.yml, tests/data/burn_in/evergreen_with_no_burn_in_task_group.yml, tests/data/burn_in/evergreen_with_no_burn_in_variants.yml, tests/data/evergreen.yml, tests/integration_test.rs
Patch:https://spruce.mongodb.com/version/630e63453066156e2ff2b9ee/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> DAG-1950: Make burn_in_tags compile task group and distro name configurable

CHANGELOG.md, Cargo.lock, Cargo.toml, src/resmoke/external_cmd.rs, src/resmoke/resmoke_proxy.rs
[Successful patch](https://spruce.mongodb.com/task/mongodb_mongo_master_generate_tasks_for_version_version_gen_patch_d8ce3ee2e020d1ab2fa611a2a0f0a222b06b9779_63222a26e3c33123f006c13a_22_09_14_19_23_34/logs?execution=0)
[Patch with resmoke error](https://evergreen.mongodb.com/filediff/631badee0305b92ba80bceb6/?file_name=evergreen%2Fbuild_variant_generate.sh&patch_number=0)
[Error log](https://evergreen.mongodb.com/lobster/evergreen/task/mongosync_rhel80_build_variant_gen_patch_ea007a3f028bccbc41f5d5a60df1d4e0dffc3503_631badee0305b92ba80bceb6_22_09_09_21_19_51/1/task#bookmarks=0%2C501&l=1&shareLine=479)
=> DAG-1935: Have better messages when doing resmoke calls

CHANGELOG.md, Cargo.lock, Cargo.toml, src/main.rs, src/task_types/burn_in_tests.rs, src/task_types/fuzzer_tasks.rs, src/task_types/resmoke_config_writer.rs, src/task_types/resmoke_tasks.rs, src/utils/task_name.rs, tests/integration_test.rs
[Patch](https://spruce.mongodb.com/version/63408e4432f417482bd32150/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
=> DAG-1987: Remove _misc sub-task creation for generated tasks

CHANGELOG.md, Cargo.toml, src/lib.rs, src/task_types/burn_in_tests.rs
It turned out that only the `build_by_id()` EVG API was broken. `tasks_by_build()` worked well as an alternative so I'm uncommenting the temporary excluded code from #51.
One other change is to add the `compile_variant` expansion that I had missed in the original PR.
I'm going to skip the line and merge this given the code was a part of #51. Please feel free to revert/amend if anything doesn't look right.
=> DAG-2208 uncomment workaround for EVG issue

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib.rs, src/services/config_extraction.rs, src/task_types/burn_in_tests.rs, src/task_types/fuzzer_tasks.rs, src/task_types/generated_suite.rs, src/task_types/resmoke_tasks.rs
Ended up not doing too much of refactoring. Added some tests to make sure that distros are applying correctly.
Some patches in evergreen:
https://spruce.mongodb.com/version/63bffc2557e85a1deec2a923
https://spruce.mongodb.com/version/63bffc4361837d7a95e8f92c
https://spruce.mongodb.com/version/63bffd1e9ccd4e371e860fbe
I don't see any failure in patches being related to distros that tasks are running on. I also looked through json configuration files generated by mongo-task-generator in those patches and didn't find any issue with distros as well.
=> DAG-2316 Apply appropriate large distros to tasks according to build variant configurations

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/generating_tasks.md, evergreen.yml, src/evergreen_names.rs, src/lib.rs, src/task_types/burn_in_tests.rs, tests/data/burn_in/evergreen_with_empty_burn_in_variants.yml, tests/data/burn_in/evergreen_with_no_burn_in_task_group.yml, tests/data/burn_in/evergreen_with_no_burn_in_variants.yml, tests/data/evergreen.yml, tests/integration_test.rs
Switched the use of compile variant of the variant where the burn_in_tags task is configured to the variant that we base generated burn_in_tags variant off of.
For example we have burn_in_tags_gen task configured on `enterprise-rhel-80-64-bit-dynamic-all-feature-flags-required` variant. The following configuration is setup for this variant:
```
- name: enterprise-rhel-80-64-bit-dynamic-all-feature-flags-required
...
expansions:
burn_in_tag_buildvariants: >-
enterprise-rhel-80-64-bit-inmem
enterprise-rhel-80-64-bit-multiversion
burn_in_tag_compile_task_dependency: archive_dist_test_debug
compile_variant: linux-x86-dynamic-compile-required
```
Instead of using `compile_variant` configuration from this variant we are using configurations from `enterprise-rhel-80-64-bit-inmem` and …
=> DAG-2233 Use the compile variant of burn_in_tag_buildvariant for generating burn_in_tags

CHANGELOG.md, Cargo.toml, src/resmoke/external_cmd.rs
https://jira.mongodb.org/browse/DAG-2476
Currently, when resmoke throws an exception, the stack traceback is logged as one line, which makes it difficult to see. This, PR implements a change that prints each line of traceback in a separate line, to make it more readable. The original logging remains the same.
Before:
After:
=> DAG-2476 Make resmoke errors easier to see in version_gen

CHANGELOG.md, Cargo.lock, Cargo.toml, src/resmoke/resmoke_suite.rs, src/task_types/multiversion.rs, src/task_types/resmoke_config_writer.rs, tests/mocks/resmoke.py
https://jira.mongodb.org/browse/SERVER-74832
This PR introduces changes to propagate description of a suite to its sub-suites when a task is split using task-generator
Patch Build before changes:
https://spruce.mongodb.com/version/645175087742ae5f18f7a73b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Patch Build after changes:
https://spruce.mongodb.com/version/64517d633e8e866fe3584115/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Before:
After:
=> SERVER-74832 Resmoke description field does not work for suites that get split up

CHANGELOG.md
turns out "evergreen merge" does not trigger the release pipeline
=> SERVER-81436 fix release pipeline

CHANGELOG.md, Cargo.lock, Cargo.toml, docs/generating_tasks.md, src/evergreen_names.rs, src/services/config_extraction.rs, src/task_types/fuzzer_tasks.rs, src/task_types/generated_suite.rs, src/task_types/resmoke_tasks.rs
for https://jira.mongodb.org/browse/BF-29398 we need to increase the distro size of one generated task but currently generated tasks only allow the variant distro or the configured large distro for a variant. This ticket will add a third option so we will not have to increase the distro size for every task unnecessarily. 
Here are the server changes that are necessary for this https://github.com/10gen/mongo/pull/19089
use_xlarge_distro acts as use_large_distro for variants that do not have xlarge_distro_name configured.
=> DEVPROD-4926 add use_xlarge_distro option to mongo-task-generator

CHANGELOG.md, Cargo.lock, Cargo.toml, src/evergreen_names.rs, src/lib.rs, src/services/config_extraction.rs, src/task_types/burn_in_tests.rs, src/task_types/fuzzer_tasks.rs, src/task_types/multiversion.rs, src/task_types/resmoke_tasks.rs
Rust noob
Our git future multiversion variant would not run last continuous tests when last_lts = last_continuous. This allows variants to override the `last_versions` setting in the multiversion_config so they will always have the versions they want.
The UNIQUE_GEN_SUFFIX_EXPANSION is needed so we do not have duplicate tasks with the same name because there can now be conflicts.
Here is a PB on the mongodb-mongo-master project with this implemented: https://spruce.mongodb.com/version/65de6b463e8e8682d69db4f4
The mongo changes for this are here https://github.com/10gen/mongo/pull/19452
=> DEVPROD-5087 allow variants to override last_versions

CHANGELOG.md, Cargo.lock, Cargo.toml, src/evergreen/evg_config_utils.rs, src/resmoke/burn_in_proxy.rs, src/task_types/burn_in_tests.rs, tests/mocks/burn_in_tests.py
This supports the change of the output format of `buildscripts/burn_in_tests.py run --yaml` that will be done in [SERVER-91556](https://jira.mongodb.org/browse/SERVER-91556)
from 
```yaml
discovered_tasks:
- task_name: jsCore
test_list:
- tests/data/tests/test_0.js
```
to
```yaml
discovered_tasks:
- task_name: jsCore
suites:
- suite_name: jsCore
test_list:
- tests/data/tests/test_0.js
```
This way it generates only affected multiversion sub suites.
🌲 https://spruce.mongodb.com/version/669f8820b5f6690007ef9990 - before
🌲 https://spruce.mongodb.com/version/66a24531e80fa500070be58b - after
=> DEVPROD-9236 Update burn-in task generation to handle each multiversion sub-suite individually

.github/workflows/release.yml
Should fix error
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
=> Update deprecated github workflow actions

CHANGELOG.md, Cargo.lock, Cargo.toml
Context
---
Incorporating this change https://github.com/evergreen-ci/shrub-rs/pull/4
Testing
---
Verified locally that `ec2.assume_role` command doesn't cause parsing errors:
```diff
diff --git a/etc/evergreen_yml_components/tasks/misc_tasks.yml b/etc/evergreen_yml_components/tasks/misc_tasks.yml
index da78b325672..08f34c72f61 100644
--- a/etc/evergreen_yml_components/tasks/misc_tasks.yml
+++ b/etc/evergreen_yml_components/tasks/misc_tasks.yml
@@ -1576,3 +1576,11 @@ tasks:
- func: "set up venv"
- func: "upload pip requirements"
- func: "generate version validation"
+
+  - name: test_ec2_assume_role_command
+    commands:
+      - command: ec2.assume_role
+        params:
+          role_arn: "${ecr_role_arn}"
+          policy: "{}"
+          duration_seconds: 900
```
```bash
mongo % …
```
=> DEVPROD-12834 Update shrub-rs dependency that includes ec2.assume_role command

CHANGELOG.md, Cargo.lock, Cargo.toml
shrub-rs 0.5.5 has a new Evergreen command that will prevent crashes in `mongo-task-generator`
=> DEVPROD-14172: update shrub-rs to 0.5.5

CHANGELOG.md, Cargo.lock, Cargo.toml, src/task_types/resmoke_tasks.rs
The tests returned by resmoke's test discovery for a task may be empty. The codepath for splitting the task when stats from evergreen are successfully collected handles this, but the fallback method here naively did not. An empty list of sub-suites should be returned to match behavior.
=> DEVPROD-14354 avoid a division-by-zero when processing empty suites

CHANGELOG.md, Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs, src/resmoke/resmoke_proxy.rs
This will ensure that build variants that override fully disabled feature flags will include the tests that are expected to run.
In total, the generated suite configs in mongodb-mongo-master grow by 1.3% since they now include a few more tests, but when run, the feature flag filtering is applied as expected. Only variants that use --additionalFeatureFlags to override fully_disabled_feature_flags.yml may have a increase in what tests actually run.
=> DEVPROD-16742 Include fully disabled feature flags when using resmoke's test-discovery

Cargo.lock, Cargo.toml, docs/generating_tasks.md, src/lib.rs, src/services/config_extraction.rs, src/task_types/resmoke_tasks.rs, tests/data/evergreen.yml, tests/integration_test.rs
This extends the capability for configuring the number of sub-tasks to all generated task types (previously this was only available for fuzzer tasks). The number of generated subtasks is now configurable using `num_tasks`, with the default still being to use 5.
Usage:
```
- <<: *gen_task_template
name: auth_gen
tags: ["auth"]
commands:
- func: "generate resmoke tasks"
vars:
num_tasks: 10
```
=> DEVPROD-16911 make number of sub-tasks configurable

src/evergreen/evg_config.rs, src/lib.rs, src/main.rs, src/services/config_extraction.rs, src/task_types/burn_in_tests.rs, src/task_types/resmoke_tasks.rs
The heuristic for determining sub-task counts becomes, in priority:
1. The `num_tasks` specified in Evergreen YAML for the gen task.
2. If the task runs on a required build variant and surpasses a threshold of total test runtime, allocate additional subtasks based on the total test runtime of the suite, up to a maximum.
3. Use the default 5 subtasks.
=> DEVPROD-17023 Split large tasks on required variants based on total test runtime

CHANGELOG.md, Cargo.lock, Cargo.toml, src/task_types/burn_in_tests.rs
This ensures that the `select_multiversion_binaries` task is created and run when a burn-in task is multiversion. If the generated task needs to depend on `select_multiversion_binaries`, it adds the dependency to the task reference, overriding the variant-wide dependencies.
=> DEVPROD-17817 add dependencies for multiversion binary selection on burn-in task references
